# Generated by Django 4.1 on 2022-08-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InteractiveLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='conv',
        ),
        migrations.AddField(
            model_name='language',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='InteractiveLearningApp.conversation'),
        ),
    ]
